<?php

namespace Container3c3PXkd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NV1GnmjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nV1Gnmj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nV1Gnmj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'favoritesRepository' => ['privates', 'App\\Repository\\FavoritesRepository', 'getFavoritesRepositoryService', true],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'entityManager' => '?',
            'favoritesRepository' => 'App\\Repository\\FavoritesRepository',
            'tokenStorage' => '?',
        ]);
    }
}
