<?php

namespace Container3c3PXkd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecetteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Recette' shared autowired service.
     *
     * @return \App\Entity\Recette
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Recette.php';

        return $container->privates['App\\Entity\\Recette'] = new \App\Entity\Recette();
    }
}
