<?php

namespace ContainerLq70fgZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gv7c05fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gv7c05f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gv7c05f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'recetteRepository' => ['privates', 'App\\Repository\\RecetteRepository', 'getRecetteRepositoryService', true],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'entityManager' => '?',
            'recetteRepository' => 'App\\Repository\\RecetteRepository',
            'tokenStorage' => '?',
        ]);
    }
}
