<?php

namespace ContainerLq70fgZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GW4Htf0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gW4Htf0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gW4Htf0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recipe' => ['privates', '.errored..service_locator.gW4Htf0.App\\Entity\\Recette', NULL, 'Cannot autowire service ".service_locator.gW4Htf0": it needs an instance of "App\\Entity\\Recette" but this type has been excluded in "config/services.yaml".'],
        ], [
            'recipe' => 'App\\Entity\\Recette',
        ]);
    }
}
