<?php

namespace ContainerLq70fgZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kil9TtEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kil9TtE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kil9TtE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AuthController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\DefaultController::displayOne' => ['privates', '.service_locator.Gv7c05f', 'get_ServiceLocator_Gv7c05fService', true],
            'App\\Controller\\DefaultController::index' => ['privates', '.service_locator.UyLPncx', 'get_ServiceLocator_UyLPncxService', true],
            'App\\Controller\\RecetteController::addNewRecipe' => ['privates', '.service_locator.gW4Htf0', 'get_ServiceLocator_GW4Htf0Service', true],
            'App\\Controller\\RecetteController::canAccessRecipe' => ['privates', '.service_locator.gW4Htf0', 'get_ServiceLocator_GW4Htf0Service', true],
            'App\\Controller\\RecetteController::createNewRecipe' => ['privates', '.service_locator.Gv7c05f', 'get_ServiceLocator_Gv7c05fService', true],
            'App\\Controller\\RecetteController::deleteRecipe' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RecetteController::editRecipe' => ['privates', '.service_locator.3euhKkW', 'get_ServiceLocator_3euhKkWService', true],
            'App\\Controller\\RecetteController::getUserRecipes' => ['privates', '.service_locator.1pfjji.', 'get_ServiceLocator_1pfjji_Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.V6D1oJY', 'get_ServiceLocator_V6D1oJYService', true],
            'App\\Controller\\UserController::getFavorites' => ['privates', '.service_locator.nV1Gnmj', 'get_ServiceLocator_NV1GnmjService', true],
            'App\\Controller\\UserController::removeFavorite' => ['privates', '.service_locator.1pfjji.', 'get_ServiceLocator_1pfjji_Service', true],
            'App\\Controller\\UserController::setFavorite' => ['privates', '.service_locator.nV1Gnmj', 'get_ServiceLocator_NV1GnmjService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AuthController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\DefaultController:displayOne' => ['privates', '.service_locator.Gv7c05f', 'get_ServiceLocator_Gv7c05fService', true],
            'App\\Controller\\DefaultController:index' => ['privates', '.service_locator.UyLPncx', 'get_ServiceLocator_UyLPncxService', true],
            'App\\Controller\\RecetteController:addNewRecipe' => ['privates', '.service_locator.gW4Htf0', 'get_ServiceLocator_GW4Htf0Service', true],
            'App\\Controller\\RecetteController:canAccessRecipe' => ['privates', '.service_locator.gW4Htf0', 'get_ServiceLocator_GW4Htf0Service', true],
            'App\\Controller\\RecetteController:createNewRecipe' => ['privates', '.service_locator.Gv7c05f', 'get_ServiceLocator_Gv7c05fService', true],
            'App\\Controller\\RecetteController:deleteRecipe' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RecetteController:editRecipe' => ['privates', '.service_locator.3euhKkW', 'get_ServiceLocator_3euhKkWService', true],
            'App\\Controller\\RecetteController:getUserRecipes' => ['privates', '.service_locator.1pfjji.', 'get_ServiceLocator_1pfjji_Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.V6D1oJY', 'get_ServiceLocator_V6D1oJYService', true],
            'App\\Controller\\UserController:getFavorites' => ['privates', '.service_locator.nV1Gnmj', 'get_ServiceLocator_NV1GnmjService', true],
            'App\\Controller\\UserController:removeFavorite' => ['privates', '.service_locator.1pfjji.', 'get_ServiceLocator_1pfjji_Service', true],
            'App\\Controller\\UserController:setFavorite' => ['privates', '.service_locator.nV1Gnmj', 'get_ServiceLocator_NV1GnmjService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AuthController::login' => '?',
            'App\\Controller\\DefaultController::displayOne' => '?',
            'App\\Controller\\DefaultController::index' => '?',
            'App\\Controller\\RecetteController::addNewRecipe' => '?',
            'App\\Controller\\RecetteController::canAccessRecipe' => '?',
            'App\\Controller\\RecetteController::createNewRecipe' => '?',
            'App\\Controller\\RecetteController::deleteRecipe' => '?',
            'App\\Controller\\RecetteController::editRecipe' => '?',
            'App\\Controller\\RecetteController::getUserRecipes' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\UserController::getFavorites' => '?',
            'App\\Controller\\UserController::removeFavorite' => '?',
            'App\\Controller\\UserController::setFavorite' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AuthController:login' => '?',
            'App\\Controller\\DefaultController:displayOne' => '?',
            'App\\Controller\\DefaultController:index' => '?',
            'App\\Controller\\RecetteController:addNewRecipe' => '?',
            'App\\Controller\\RecetteController:canAccessRecipe' => '?',
            'App\\Controller\\RecetteController:createNewRecipe' => '?',
            'App\\Controller\\RecetteController:deleteRecipe' => '?',
            'App\\Controller\\RecetteController:editRecipe' => '?',
            'App\\Controller\\RecetteController:getUserRecipes' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\UserController:getFavorites' => '?',
            'App\\Controller\\UserController:removeFavorite' => '?',
            'App\\Controller\\UserController:setFavorite' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
