<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3c3PXkd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3c3PXkd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3c3PXkd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3c3PXkd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3c3PXkd\App_KernelDevDebugContainer([
    'container.build_hash' => '3c3PXkd',
    'container.build_id' => '02e6df03',
    'container.build_time' => 1706891805,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3c3PXkd');
